### ISSUE TITLE
Jellyfin not starting with windows startup

### ISSUE THREAD

**Issue by torrentguy** [jellyfin/jellyfin-windows-tray#10]
Ive even tried to put a shortcut in the startup programs folder of windows but it still doesn't start automatically

**To Reproduce**

1. install jellyfin as a service

**Expected behavior**

It's expected to start the tray icon and start the service itself

**System (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Jellyfin Version: 10.4.1

**Comment by patrickonparker** [comment]
If anyone else is having this issue, I had to update the service to log on as the local system account,
![image](https://user-images.githubusercontent.com/19916853/81973379-0d8a1980-95f2-11ea-90e2-8ce1d5870391.png)

**Comment by jchurchward** [comment]
For anyone seeking a solution to run Jellyfin as a service, here's what worked for me. I initially tried installing Jellyfin using the advanced installation option, but encountered issues where Jellyfin would run but I couldn't authenticate—it was completely broken. Instead, I installed NSSM and configured it to run Jellyfin as a service by pointing to C:\Program Files\Jellyfin\Server\jellyfin-windows-tray\Jellyfin.Windows.Tray.exe.
