### ISSUE TITLE
tray can't launch properly

### ISSUE THREAD

**Issue by s0urcelab** [jellyfin/jellyfin-windows-tray#12]
everything works fine till i clean up user temp folder (%USERPROFILE%\AppData\Local\Temp).
since then i can't launch tray anymore, and no warning or error show up, it just can't work.
ps: i have tried to reinstall the whole application and no helping.

**Comment by anthonylavado** [comment]
Try following the steps here. It’s likely the program thinks it’s extracted, but it’s not.
I plan on fixing that before the next version.

https://github.com/jellyfin/jellyfin/issues/2032#issuecomment-562814135

**Comment by s0urcelab** [comment]
Before your reply i found if i rename JellyfinTray.exe to another name( JellyfinTray2222 ), it works well.
there are several folders like "JellyfinTray\l2cxugcr.jn2","JellyfinTray2222\l2cxugcr.jn2"  in %temp%\.net , but "JellyfinTray\l2cxugcr.jn2" is empty, so i copied all files from "JellyfinTray2222\l2cxugcr.jn2" then problem fixed.
thanks all the same!!!
